extends: default

rules:
  line-length:
    max: 140
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    level: warning
  comments-indentation: {level: warning}
  document-start: {present: false}

