name: CI

on:
  push:
    branches: [ main, trunk, master ]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        signing: [ "false", "true" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.signing }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.signing }}-
            ${{ runner.os }}-buildx-

      - name: Build test image (signing=${{ matrix.signing }})
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: shiplog-tests:ci
          build-args: |
            ENABLE_SIGNING=${{ matrix.signing }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move buildx cache (persist across steps)
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Run bats in container (mount repo)
        run: |
          docker run --rm -v "$PWD":/workspace shiplog-tests:ci

      - name: Upload test artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-signing-${{ matrix.signing }}
          path: |
            tests/output/**
            tests/**/*.log
          if-no-files-found: ignore
