name: Lint

"on":
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run shellcheck (non-blocking)
        run: |
          set +e
          echo "ShellCheck version:" && shellcheck --version
          SH_FILES=$(git ls-files | grep -E '(^bin/git-shiplog$|^contrib/hooks/[^/]+$|\.sh$)' || true)
          if [ -n "$SH_FILES" ]; then
            shellcheck -S style -s bash $SH_FILES || true
          else
            echo "No shell files found"
          fi

  markdownlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2
      - name: Run markdownlint-cli2 (non-blocking)
        run: |
          set +e
          markdownlint-cli2 || true

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
      - name: Run yamllint
        run: |
          set -euo pipefail
          yamllint -v
          yamllint -f github .github/workflows docs/**/*.yml docs/**/*.yaml || true
