name: Lint

"on":
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      shell: ${{ steps.filter.outputs.shell }}
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            shell:
              - 'bin/git-shiplog'
              - 'contrib/hooks/**'
              - '**/*.sh'
            markdown:
              - '**/*.md'
  shellcheck:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.shell == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: |
          set -euo pipefail
          echo "ShellCheck version:" && shellcheck --version
          # Build a safe array of shell files (handles spaces/newlines)
          mapfile -t SH_FILES < <(git ls-files | grep -E '(^bin/git-shiplog$|^contrib/hooks/[^/]+$|\.sh$)' || true)
          if [ "${#SH_FILES[@]}" -gt 0 ]; then
            shellcheck -e SC2034 -S style -s bash "${SH_FILES[@]}"
          else
            echo "No shell files found"
          fi

  markdownlint:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.markdown == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2@0.15.0
      - name: Get changed markdown files (PRs)
        if: github.event_name == 'pull_request'
        id: changed-markdown
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.md
      - name: Run markdownlint-cli2
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            if [ "${{ steps.changed-markdown.outputs.any_changed }}" != "true" ]; then
              echo "No changed markdown files; skipping."
              exit 0
            fi
            # Lint only changed Markdown files (avoids baseline noise)
            files='${{ steps.changed-markdown.outputs.all_changed_files }}'
            echo "Linting changed files: $files"
            markdownlint-cli2 $files
          else
            # On push (e.g., main), lint entire repo
            markdownlint-cli2
          fi

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
      - name: Run yamllint
        run: |
          set -euo pipefail
          yamllint -v
          shopt -s globstar nullglob
          files=( .github/workflows/*.yml .github/workflows/*.yaml docs/**/*.yml docs/**/*.yaml )
          if [ ${#files[@]} -gt 0 ]; then
            yamllint -f github "${files[@]}"
          fi

  policy_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install ajv-cli
        run: npm install -g ajv-cli
      - name: Validate policy files against schema (non-blocking for now)
        run: |
          set -euo pipefail
          echo "Validating policy files with ajv"
          shopt -s globstar nullglob
          files=( .shiplog/policy.json docs/**/*.policy.json examples/**/*.policy.json )
          if [ ${#files[@]} -eq 0 ]; then
            echo "No policy files found; skipping."
            exit 0
          fi
          ajv validate --spec=draft2020 -s examples/policy.schema.json -d "${files[@]}" || true
