name: Lint

"on":
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: |
          echo "ShellCheck version:" && shellcheck --version
          SH_FILES=$(git ls-files | grep -E '(^bin/git-shiplog$|^contrib/hooks/[^/]+$|\.sh$)' || true)
          if [ -n "$SH_FILES" ]; then
            shellcheck -e SC2034 -S style -s bash $SH_FILES || true
          else
            echo "No shell files found"
          fi

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2
      - name: Run markdownlint-cli2
        run: |
          markdownlint-cli2 || true

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
      - name: Run yamllint
        run: |
          set -euo pipefail
          yamllint -v
          shopt -s globstar nullglob
          files=( .github/workflows/*.yml .github/workflows/*.yaml docs/**/*.yml docs/**/*.yaml )
          if [ ${#files[@]} -gt 0 ]; then
            yamllint -f github "${files[@]}"
          fi

  policy_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install ajv-cli
        run: npm install -g ajv-cli
      - name: Validate policy files against schema
        run: |
          set -euo pipefail
          echo "Validating policy files with ajv"
          shopt -s globstar nullglob
          files=( .shiplog/policy.json docs/**/*.policy.json examples/**/*.policy.json )
          if [ ${#files[@]} -eq 0 ]; then
            echo "No policy files found; skipping."
            exit 0
          fi
          ajv validate --spec=draft2020 -s examples/policy.schema.json -d "${files[@]}" || true
