name: Task Progress Check

on:
  pull_request:
    branches: [main]

jobs:
  task-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Update bars
        run: bash scripts/update-task-progress.sh
      - name: Ensure no changes
        run: |
          if ! git diff --exit-code; then
            echo "Progress bars out of date. Run: make progress" >&2
            exit 1
          fi
